// Code generated by protoc-gen-go.
// source: media/proto/data.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	media/proto/data.proto

It has these top-level messages:
	Store
	StoreStream
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Store_DataType int32

const (
	Store_MOBILE Store_DataType = 0
	Store_HOME   Store_DataType = 1
	Store_WORK   Store_DataType = 2
)

var Store_DataType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Store_DataType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Store_DataType) String() string {
	return proto1.EnumName(Store_DataType_name, int32(x))
}
func (Store_DataType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Store struct {
	Id   int32         `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string        `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Data []*Store_Data `protobuf:"bytes,3,rep,name=data" json:"data,omitempty"`
}

func (m *Store) Reset()                    { *m = Store{} }
func (m *Store) String() string            { return proto1.CompactTextString(m) }
func (*Store) ProtoMessage()               {}
func (*Store) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Store) GetData() []*Store_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type Store_Data struct {
	Id     int32          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name   string         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email  string         `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Number string         `protobuf:"bytes,4,opt,name=number" json:"number,omitempty"`
	Type   Store_DataType `protobuf:"varint,5,opt,name=type,enum=proto.Store_DataType" json:"type,omitempty"`
}

func (m *Store_Data) Reset()                    { *m = Store_Data{} }
func (m *Store_Data) String() string            { return proto1.CompactTextString(m) }
func (*Store_Data) ProtoMessage()               {}
func (*Store_Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type StoreStream struct {
	Stores []*Store `protobuf:"bytes,1,rep,name=stores" json:"stores,omitempty"`
}

func (m *StoreStream) Reset()                    { *m = StoreStream{} }
func (m *StoreStream) String() string            { return proto1.CompactTextString(m) }
func (*StoreStream) ProtoMessage()               {}
func (*StoreStream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StoreStream) GetStores() []*Store {
	if m != nil {
		return m.Stores
	}
	return nil
}

func init() {
	proto1.RegisterType((*Store)(nil), "proto.Store")
	proto1.RegisterType((*Store_Data)(nil), "proto.Store.Data")
	proto1.RegisterType((*StoreStream)(nil), "proto.StoreStream")
	proto1.RegisterEnum("proto.Store_DataType", Store_DataType_name, Store_DataType_value)
}

func init() { proto1.RegisterFile("media/proto/data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x8f, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x4d, 0x9a, 0x94, 0xf9, 0x26, 0xa3, 0x3e, 0x74, 0x04, 0x4f, 0xa5, 0x28, 0x54, 0x0f,
	0x1d, 0x6c, 0xdf, 0x40, 0x1c, 0x28, 0x3a, 0x0a, 0x99, 0xe0, 0x39, 0xa3, 0xef, 0x50, 0x30, 0x6b,
	0xe9, 0xe2, 0x61, 0x67, 0xfd, 0xe0, 0x92, 0xb7, 0x09, 0x82, 0x17, 0x4f, 0xf9, 0xff, 0x7f, 0x2f,
	0xf9, 0x25, 0x81, 0xa9, 0xa7, 0xa6, 0x75, 0xb3, 0x7e, 0xe8, 0x42, 0x37, 0x6b, 0x5c, 0x70, 0x15,
	0x47, 0xd4, 0xbc, 0x14, 0x5f, 0x12, 0xf4, 0x3a, 0x74, 0x03, 0xe1, 0x04, 0x64, 0xdb, 0x18, 0x91,
	0x8b, 0x52, 0x5b, 0xd9, 0x36, 0x88, 0xa0, 0xb6, 0xce, 0x93, 0x91, 0xb9, 0x28, 0x4f, 0x2d, 0x67,
	0xbc, 0x01, 0x15, 0x15, 0x26, 0xc9, 0x93, 0x72, 0x3c, 0x3f, 0x3f, 0xa8, 0x2a, 0x3e, 0x5f, 0x3d,
	0xb8, 0xe0, 0x2c, 0x8f, 0xaf, 0x3e, 0x05, 0xa8, 0x58, 0xff, 0xe5, 0xbc, 0x00, 0x4d, 0xde, 0xb5,
	0xef, 0x26, 0x61, 0x78, 0x28, 0x38, 0x85, 0x74, 0xfb, 0xe1, 0x37, 0x34, 0x18, 0xc5, 0xf8, 0xd8,
	0xf0, 0x16, 0x54, 0xd8, 0xf7, 0x64, 0x74, 0x2e, 0xca, 0xc9, 0xfc, 0xf2, 0xcf, 0x0b, 0x5e, 0xf7,
	0x3d, 0x59, 0xde, 0x52, 0xdc, 0xc1, 0xe8, 0x87, 0x20, 0x40, 0xba, 0xaa, 0xef, 0x9f, 0x5e, 0x96,
	0xd9, 0x09, 0x8e, 0x40, 0x3d, 0xd6, 0xab, 0x65, 0x26, 0x62, 0x7a, 0xab, 0xed, 0x73, 0x26, 0x8b,
	0x05, 0x8c, 0xd9, 0xb1, 0x0e, 0x03, 0x39, 0x8f, 0xd7, 0x90, 0xee, 0x62, 0xdd, 0x19, 0xc1, 0x3f,
	0x3d, 0xfb, 0x7d, 0x8f, 0x3d, 0xce, 0x36, 0x29, 0xc3, 0xc5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xdd, 0x91, 0xcc, 0x3f, 0x63, 0x01, 0x00, 0x00,
}
